#ifndef gcal__enums__
#define gcal__enums__

#include "stdafx.h"

enum MahadvadasiType {
	EV_NULL              = 0x100,
    EV_SUDDHA            = 0x101,
    EV_UNMILANI          = 0x102,
    EV_VYANJULI          = 0x103,
    EV_TRISPRSA          = 0x104,
    EV_UNMILANI_TRISPRSA = 0x105,
    EV_PAKSAVARDHINI     = 0x106,
    EV_JAYA              = 0x107,
    EV_JAYANTI           = 0x108,
    EV_PAPA_NASINI       = 0x109,
    EV_VIJAYA            = 0x110
};


enum FastType {
    FAST_NULL      = 0x000,
    FAST_NOON      = 0x201,
    FAST_SUNSET    = 0x202,
    FAST_MOONRISE  = 0x203,
    FAST_DUSK      = 0x204,
    FAST_MIDNIGHT  = 0x205,
    FAST_EKADASI   = 0x206,
    FAST_DAY       = 0x207
};

enum FeastType {
	FEAST_NULL                 = 0,
	FEAST_TODAY_FAST_YESTERDAY = 1,
	FEAST_TOMMOROW_FAST_TODAY  = 2
};

enum SpecialFestivalId {
	SPEC_RETURNRATHA    =  3,
	SPEC_HERAPANCAMI    =  4,
	SPEC_GUNDICAMARJANA =  5,
	SPEC_GOVARDHANPUJA  =  6,
	SPEC_VAMANADVADASI  =  7,
	SPEC_VARAHADVADASI  =  8,
	SPEC_RAMANAVAMI     =  9,
	SPEC_JANMASTAMI     = 10,
	SPEC_RATHAYATRA     = 11,
	SPEC_GAURAPURNIMA   = 12,
	SPEC_NANDAUTSAVA    = 13,
	SPEC_MISRAFESTIVAL  = 14,
	SPEC_PRABHAPP       = 15
};


enum EkadasiParanaType {
	EP_TYPE_NULL    = 0,
	EP_TYPE_3DAY    = 1,
	EP_TYPE_4TITHI  = 2,
	EP_TYPE_NAKEND  = 3,
	EP_TYPE_SUNRISE = 4,
	EP_TYPE_TEND    = 5
};

enum CaturmasyaCodes {
	CMASYA_SYSTEM_PURNIMA = 13,
	CMASYA_SYSTEM_PRATIPAT = 14,
	CMASYA_SYSTEM_EKADASI = 15,
	CMASYA_SYSTEM_MASK = 0xff,

	CMASYA_MONTH_1 = 0x100,
	CMASYA_MONTH_2 = 0x200,
	CMASYA_MONTH_3 = 0x300,
	CMASYA_MONTH_4 = 0x400,
	CMASYA_MONTH_MASK = 0xf00,

	CMASYA_DAY_FIRST = 0x1000,
	CMASYA_DAY_LAST  = 0x2000,
	CMASYA_DAY_MASK  = 0xf000
};


enum MasaId {
	MADHUSUDANA_MASA = 0,
	TRIVIKRAMA_MASA = 1,
	VAMANA_MASA = 2,
	SRIDHARA_MASA = 3,
	HRSIKESA_MASA = 4,
	PADMANABHA_MASA = 5,
	DAMODARA_MASA = 6,
	KESAVA_MASA = 7,
	NARAYANA_MASA = 8,
	MADHAVA_MASA = 9,
	GOVINDA_MASA = 10,
	VISNU_MASA = 11,
	ADHIKA_MASA = 12
};

enum SankrantiId {
	MESHA_SANKRANTI = 0,
	VRSABHA_SANKRANTI = 1,
	MITHUNA_SANKRANTI = 2,
	KATAKA_SANKRANTI = 3,
	SIMHA_SANKRANTI = 4,
	KANYA_SANKRANTI = 5,
	TULA_SANKRANTI = 6,
	VRSCIKA_SANKRANTI = 7,
	DHANUS_SANKRANTI = 8,
	MAKARA_SANKRANTI = 9,
	KUMBHA_SANKRANTI = 10,
	MINA_SANKRANTI = 11
};

enum PaksaId {
	KRSNA_PAKSA = 0,
	GAURA_PAKSA = 1
};

enum TithiId {
	TITHI_KRSNA_PRATIPAT = 0,
	TITHI_KRSNA_DVITIYA = 1,
	TITHI_KRSNA_TRITIYA = 2,
	TITHI_KRSNA_CATURTI = 3,
	TITHI_KRSNA_PANCAMI = 4,
	TITHI_KRSNA_SASTI = 5,
	TITHI_KRSNA_SAPTAMI = 6,
	TITHI_KRSNA_ASTAMI = 7,
	TITHI_KRSNA_NAVAMI = 8,
	TITHI_KRSNA_DASAMI = 9,
	TITHI_KRSNA_EKADASI = 10,
	TITHI_KRSNA_DVADASI = 11,
	TITHI_KRSNA_TRAYODASI = 12,
	TITHI_KRSNA_CATURDASI = 13,
	TITHI_AMAVASYA = 14,
	TITHI_GAURA_PRATIPAT = 15,
	TITHI_GAURA_DVITIYA = 16,
	TITHI_GAURA_TRITIYA = 17,
	TITHI_GAURA_CATURTI = 18,
	TITHI_GAURA_PANCAMI = 19,
	TITHI_GAURA_SASTI = 20,
	TITHI_GAURA_SAPTAMI = 21,
	TITHI_GAURA_ASTAMI = 22,
	TITHI_GAURA_NAVAMI = 23,
	TITHI_GAURA_DASAMI = 24,
	TITHI_GAURA_EKADASI = 25,
	TITHI_GAURA_DVADASI = 26,
	TITHI_GAURA_TRAYODASI = 27,
	TITHI_GAURA_CATURDASI = 28,
	TITHI_PURNIMA = 29
};

enum NaksatraId {
	ROHINI_NAKSATRA = 3
};

enum WeekDayId {
	DW_SUNDAY = 0,
	DW_MONDAY = 1,
	DW_TUESDAY = 2,
	DW_WEDNESDAY = 3,
	DW_THURSDAY = 4,
	DW_FRIDAY = 5,
	DW_SATURDAY = 6
};


enum KalaType {
	KT_RAHU_KALAM = 1,
	KT_YAMA_GHANTI = 2,
	KT_GULI_KALAM = 3,
	KT_VISHAGATI = 4
};

enum GlobalStringsEnum {
	GSTR_APPFOLDER = 1,
	GSTR_CONFOLDER = 2,
	GSTR_LANFOLDER = 3,
	GSTR_TEMFOLDER = 4,
	GSTR_CE_FILE   = 5,
	GSTR_CONF_FILE = 6,
	GSTR_LOC_FILE  = 7,
	GSTR_SSET_FILE = 8,
	GSTR_LOCX_FILE  = 9, /*GCAL 3.0*/
	GSTR_CEX_FILE   = 10, /*GCAL 3.0*/
	GSTR_CONFX_FILE = 11, /*GCAL 3.0*/ 
	GSTR_TZ_FILE    = 12, /*GCAL 3.0*/ 
	GSTR_COUNTRY_FILE = 13, /*GCAL 3.0*/ 
	GSTR_TEXT_FILE = 14, /*GCAL 4.1*/
	GSTR_TIPS_FILE = 15, /*GCAL 4.3*/
	GSTR_HELP_FILE = 16 /*GCAL 5.0*/

};

enum MainFrameContentType {
	MW_MODE_CAL      = 1,
	MW_MODE_EVENTS   = 2,
	MW_MODE_MASALIST = 3,
	MW_MODE_APPDAY   = 6,
	MW_MODE_TODAY    = 7
};

#endif


